config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :lessons
  resources :students
  resources :classrooms
  root "sessions#new"

  resources :users
  resources :subjects
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :classrooms, dependent: :destroy
  has_many :subjects, through: :classrooms
  has_many :students, through: :classrooms
  has_many :lessons, through: :subjects
  has_many :ratings, through: :lessons
  has_secure_password

  validates :name, presence: true, length: { minimum: 3 }, format: { with: /\A[a-zA-Z\s]+\z/, message: 'Somente letras são permitidas.' }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:show]

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "O usuário foi cadastrado com sucesso." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "O usuário foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "O usuário foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "d-flex flex-column align-items-center") do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> foram encontrados:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-3">
    <%= form.text_field :name, placeholder: "Nome", class: 'form-control' %>
  </div>

  <div class="mb-3">
  <%= form.email_field :email, placeholder: "E-mail", class: 'form-control' %>
  </div>

  <div class="mb-3">
  <%= form.password_field :password, placeholder: "Senha", class: 'form-control' %>
  </div>

  <div class="mb-3">
  <%= form.password_field :password_confirmation, placeholder: "Confirme a senha", class: 'form-control' %>
  </div>

  <div>
    <%= form.submit id:"submit", class: "btn btn-orange" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Nome:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>E-mail:</strong>
    <%= user.email %>
  </p>
</div>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Editar Usuário</h1>

  <%= render "form", user: @user %>

  <br>

  <div>
    <%= link_to "Voltar", @user, class: "text-light" %>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div class="row mt-5 pt-5">
  <div class="col-md-6 text-center">
    <%= image_tag("logo.png", width: "500px") %>
  </div>

  <div class="col-md-6 align-self-center text-center">
    <h1>Cadastre-se</h1>
    <%= render "form", user: @user %>

    <br>

    <div>
      <%= link_to "Voltar", root_path, class: "text-light" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <%= render @user %>

  <div>
    <%= link_to "Editar usuário", edit_user_path(@user), :class => "btn btn-orange mx-2" %>
    <%= link_to "Turmas", classrooms_path(@user), :class => "btn btn-orange mx-2" %>
    <%= link_to "Disciplinas", subjects_path(@user), :class => "btn btn-orange mx-2" %>
    <%= link_to "Alunos", students_path(@user), :class => "btn btn-orange mx-2" %>
    <%= link_to "Atividades", lessons_path(@user), :class => "btn btn-orange mx-2" %>
    <%= link_to "Avaliações", ratings_path(@user), :class => "btn btn-orange mx-2" %>

    <%= button_to "Apagar conta", @user, method: :delete, :class => "btn btn-danger mt-5" %>
  </div>

</div>