config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :lessons
  resources :students
  resources :classrooms
  root "sessions#new"

  resources :users
  resources :subjects
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :lesson
  belongs_to :student

  validates :grade, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10, message: 'A nota deve estar entre 0 e 10' }
  validates :description, length: { maximum: 1000 }
  validate :student_is_not_already_rated
  validate :student_is_in_lesson

  private
  def student_is_not_already_rated
    if Rating.where(lesson_id: lesson_id, student_id: student_id).exists?
      errors.add(:student, 'O aluno já foi avaliado nesta atividade')
    end
  end

  def student_is_in_lesson
    unless lesson.students.include?(student)
      errors.add(:student, 'O aluno não está na aula')
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]
  before_action :logged_in_user

  # GET /ratings or /ratings.json
  def index
    @ratings = current_user.ratings
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to rating_url(@rating), notice: "A avaliação foi cadastrada com sucesso!" }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "A avaliação foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "A avaliação foi apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rating
    @rating = current_user.ratings.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def rating_params
    params.require(:rating).permit(:grade, :description, :lesson_id, :student_id)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating, class: "d-flex flex-column align-items-center") do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> foram encontrados:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :lesson_id, "Atividade", style: "display: block" %>
    <%= collection_select(:rating, :lesson_id, Lesson.where(:subject_id => current_user.subjects), :id, :title, {:prompt => 'Selecione'} ) %>
  </div>

  <div class="mb-3">
    <%= form.label :student_id, "Estudante", style: "display: block" %>
    <%= collection_select(:rating, :student_id, Student.where(:classroom_id => current_user.classrooms), :id, :name, {:prompt => 'Selecione'} ) %>
  </div>

  <div class="my-3">
    <%= form.label :grade, "Nota", style: "display: block" %>
    <%= form.text_field :grade, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descrição", style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit id:"submit", class: "btn btn-orange" %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">

  <p>
    <strong>Atividade:</strong>
    <%= rating.lesson.title %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= rating.grade %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= rating.description %>
  </p>

  <p>
    <strong>Estudante:</strong>
    <%= rating.student.name %>
  </p>

  <p>
    <strong>Bimestre:</strong>
    <%= rating.lesson.bimester %>º
  </p>

  <p>
    <strong>Disciplina:</strong>
    <%= rating.lesson.subject.name %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= rating.student.classroom.name %>
  </p>

</div>

app/views/ratings/edit.html.erb
<div class="text-center">
  <h1>Editar Avaliação</h1>

  <%= render "form", rating: @rating %>

  <br>

  <div>
    <%= link_to "Voltar", ratings_path, :class => "text-light" %>
  </div>
</div>

app/views/ratings/index.html.erb
<div class="text-center">
  <h1>Avaliações</h1>

  <%= link_to "Cadastrar avaliação", new_rating_path, :class => "btn btn-orange my-5" %>

  <div id="ratings">
    <% @ratings.each do |rating| %>
      <div class="d-flex justify-content-center border m-2">
        <div class="m-2">
          <%= render rating %>
        </div>

        <div class="m-2">
          <%= link_to "Ver avaliações", rating, :class => "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ratings/new.html.erb
<div class="text-center">
  <h1>Cadastrar Avaliação</h1>

  <%= render "form", rating: @rating %>

  <br>

  <div>
    <%= link_to "Voltar para avaliações", ratings_path, :class => "text-light" %>
  </div>
</div>

app/views/ratings/show.html.erb
<div class="text-center">
  <%= render @rating %>

  <div>
    <%= link_to "Editar essa nota", edit_rating_path(@rating), :class => "btn btn-orange mx-2" %>
    <%= link_to "Voltar", ratings_path, :class => "btn btn-orange mx-2" %>

    <%= button_to "Apagar nota", @rating, method: :delete, :class => "btn btn-danger mt-5" %>
  </div>
</div>