config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :lessons
  resources :students
  resources :classrooms
  root "sessions#new"

  resources :users
  resources :subjects
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :classroom
  has_many :students, through: :classroom
  has_many :lessons, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }, format: { with: /\A[a-zA-Z0-9\s]+\z/, message: 'Somente letras e números são permitidas.' }
  validates :year, presence: true, length: { is: 4 }, numericality: { only_integer: true }
  validate :year_equal

  def name_year
    "#{name} - #{year}"
  end

  private

  def year_equal
    unless year.equal?(self.classroom.year)
      errors.add(:base, 'Ano letivo não corresponde ao da turma.')
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]
  before_action :logged_in_user

  # GET /subjects or /subjects.json
  def index
    @subjects = current_user.subjects
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = current_user.subjects.build(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "A disciplina foi cadastrada com sucesso!" }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "A disciplina foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "A disciplina foi excluída com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = current_user.subjects.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:name, :year, :classroom_id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, class: "d-flex flex-column align-items-center") do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> foram encontrados:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :year,"Ano", style: "display: block" %>
    <%= form.text_field :year, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :classroom_id, "Turma", style: "display: block" %>
    <%= collection_select(:subject, :classroom_id, Classroom.where(:user_id => current_user), :id, :name, {:prompt => 'Selecione'} ) %>
  </div>

  <div>
    <%= form.submit id:"submit", class: "btn btn-orange" %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <p>
    <strong>Nome:</strong>
    <%= subject.name %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= subject.year %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= subject.classroom.name %>
  </p>
</div>

app/views/subjects/edit.html.erb
<div class="text-center">
  <h1>Editar Disciplina</h1>

  <%= render "form", subject: @subject %>

  <br>

  <div>
    <%= link_to "Voltar", subjects_path, :class => "text-light" %>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="text-center">
  <h1>Disciplinas</h1>

  <%= link_to "Cadastrar Disciplina", new_subject_path, :class => "btn btn-orange my-5" %>

  <div id="subjects">
    <% @subjects.each do |subject| %>
      <div class="d-flex justify-content-center border m-2">
        <div class="m-2">
          <%= render subject %>
        </div>

        <div class="m-2">
          <%= link_to "Ver disciplina", subject, :class => "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="text-center">
  <h1>Cadastrar Disciplina</h1>

  <%= render "form", subject: @subject %>

  <br>

  <div>
    <%= link_to "Voltar para disciplinas", subjects_path, :class => "text-light"%>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="text-center">
  <%= render @subject %>

  <div>
    <%= link_to "Editar disciplina", edit_subject_path(@subject), :class => "btn btn-orange mx-2" %>
    <%= link_to "Voltar", subjects_path, :class => "btn btn-orange mx-2" %>

    <%= button_to "Apagar disciplina", @subject, method: :delete, :class => "btn btn-danger mt-5" %>
  </div>
</div>