config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :lessons
  resources :students
  resources :classrooms
  root "sessions#new"

  resources :users
  resources :subjects
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :students, through: :subject
  has_many :ratings

  validates :title, presence: true, length: { minimum: 5, maximum: 20, message: 'Tamanho do titulo de 5-20 caracteres' }, format: { with: /\A[a-zA-Z0-9\s]+\z/ }
  validates :description, length: { maximum: 1000 }
  validates :delivery_date, presence: true
  validates :bimester, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 4 }
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]
  before_action :logged_in_user

  # GET /lessons or /lessons.json
  def index
    @lessons = current_user.lessons
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "A atividade foi criada com sucesso!" }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "A atividade foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "A atividade foi apagada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = current_user.lessons.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :description, :delivery_date, :bimester, :subject_id)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "d-flex flex-column align-items-center") do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> foram encontrados:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-3">
    <%= form.label :title, "Título", style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descrição", style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :delivery_date, "Data de entrega", style: "display: block" %>
    <%= form.date_field :delivery_date, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :bimester, "Bimestre", style: "display: block" %>
    <%= form.text_field :bimester, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :subject_id, "Disciplina", style: "display: block" %>
    <%= collection_select(:lesson, :subject_id, Subject.where(:classroom_id => current_user.classrooms), :id, :name_year, {:prompt => 'Selecione'} ) %>
  </div>

  <div>
    <%= form.submit id:"submit", class: "btn btn-orange" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Título:</strong>
    <%= lesson.title %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= lesson.description %>
  </p>

  <p>
    <strong>Data de entrega:</strong>
    <%= lesson.delivery_date.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Bimestre:</strong>
    <%= lesson.bimester %>º
  </p>

  <p>
    <strong>Disciplina:</strong>
    <%= lesson.subject.name %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= lesson.subject.classroom.name %>
  </p>

</div>

app/views/lessons/edit.html.erb
<div class="text-center">
  <h1>Editar Atividade</h1>

  <%= render "form", lesson: @lesson %>

  <br>

  <div>
    <%= link_to "Voltar", lessons_path, :class => "text-light" %>
  </div>
</div>

app/views/lessons/index.html.erb
<div class="text-center">
  <h1>Atividades</h1>

  <%= link_to "Cadastrar atividade", new_lesson_path, :class => "btn btn-orange my-5" %>

  <div id="lessons">
    <% @lessons.each do |lesson| %>
      <div class="d-flex justify-content-center border m-2">
        <div class="m-2">
          <%= render lesson %>
        </div>

        <div class="m-2">
          <%= link_to "Ver atividade", lesson, :class => "btn btn-orange" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="text-center">
  <h1>Cadastrar Atividade</h1>

  <%= render "form", lesson: @lesson %>

  <br>

  <div>
    <%= link_to "Voltar para atividades", lessons_path, :class => "text-light"%>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="text-center">
  <%= render @lesson %>

  <div>
    <%= link_to "Editar atividade", edit_lesson_path(@lesson), :class => "btn btn-orange mx-2" %>
    <%= link_to "Voltar", lessons_path, :class => "btn btn-orange mx-2" %>

    <%= button_to "Apagar atividade", @lesson, method: :delete, :class => "btn btn-danger mt-5" %>
  </div>
</div>